;;(require 'hyperspec)
;;(setq common-lisp-hyperspec-root "file:/usr/share/doc/hyperspec/")
;;(setq slime-net-coding-system 'utf-8-unix)
;;(setq inferior-lisp-program "sbcl")
;;(require 'slime)
;;(add-hook 'lisp-mode-hook (lambda()
;;                            (slime-mode t)
;;                            (show-parent-mode)
;;                            (global-set-key "\C-cH" 'hyperspec-lookup)))
;;(slime-setup)
